name: mother
description: My mam's project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  video_player: ^2.4.7
  page_transition: "^2.0.9"
  syncfusion_flutter_pdfviewer: ^20.4.43
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/videos/Hotel/S2-1.mp4
    - assets/videos/Hotel/S2-3.mp4
    - assets/videos/Hotel/S2-a1.mp4
    - assets/videos/Hotel/S2-2aa.mp4
    - assets/videos/Hotel/S2-a2.mp4
    - assets/videos/Hotel/S2-a3.mp4
    - assets/videos/Hotel/S2-a4.mp4
    - assets/videos/Hotel/S2-a5.mp4
    - assets/videos/Hotel/S1-1.mp4
    - assets/videos/Hotel/S1-3.mp4
    - assets/videos/Hotel/S1-a1.mp4
    - assets/videos/Hotel/S1-a2.mp4
    - assets/videos/Hotel/S1-a3.mp4
    - assets/videos/Hotel/S1-a4.mp4
    - assets/videos/Hotel/S1-a5.mp4
    - assets/videos/Hotel/S1-a6.mp4
    - assets/videos/Hotel/S3-1.mp4
    - assets/videos/Hotel/S3-2a.mp4
    - assets/videos/Hotel/S3-2b.mp4
    - assets/videos/Hotel/S3-2c.mp4
    - assets/videos/Hotel/S3-2d.mp4
    - assets/videos/Hotel/S3-2e.mp4
    - assets/videos/Hotel/S3-3.mp4
    - assets/videos/Hotel/S4-1.mp4
    - assets/videos/Hotel/S4-2a.mp4
    - assets/videos/Hotel/S4-2b.mp4
    - assets/videos/Hotel/S4-2c.mp4
    - assets/videos/Hotel/S4-2ca.mp4
    - assets/videos/Hotel/S4-2d.mp4
    - assets/videos/Hotel/S4-2e.mp4
    - assets/videos/Hotel/S4-2f.mp4
    - assets/videos/Hotel/S4-2g.mp4
    - assets/videos/Hotel/S4-2h.png
    - assets/videos/Hotel/S4-3.mp4
    - assets/videos/Restaurant/S5-1.mp4
    - assets/videos/Restaurant/S5-2-1.mp4
    - assets/videos/Restaurant/S5-2-2.mp4
    - assets/videos/Restaurant/S5-2-3.mp4
    - assets/videos/Restaurant/S5-2-4.mp4
    - assets/videos/Restaurant/S5-2-4-check.mp4
    - assets/videos/Restaurant/S5-2-5.mp4
    - assets/videos/Restaurant/S5-2-6.mp4
    - assets/videos/Restaurant/S5-2-7.png
    - assets/videos/Restaurant/S5-3.mp4
    - assets/videos/Restaurant/S6-1.mp4
    - assets/videos/Restaurant/S6-2-1.mp4
    - assets/videos/Restaurant/S6-2-2.mp4
    - assets/videos/Restaurant/S6-2-3.mp4
    - assets/videos/Restaurant/S6-2-4.mp4
    - assets/videos/Restaurant/S6-2-5.mp4
    - assets/videos/Restaurant/S6-3.mp4
    - assets/videos/Restaurant/S7-1.mp4
    - assets/videos/Restaurant/S7-2-1.mp4
    - assets/videos/Restaurant/S7-2-3.mp4
    - assets/videos/Restaurant/S7-2-4.mp4
    - assets/videos/Restaurant/S7-2-5.mp4
    - assets/videos/Restaurant/S7-3.mp4
    - assets/videos/Restaurant/S8-1.mp4
    - assets/videos/Restaurant/S8-2-1.mp4
    - assets/videos/Restaurant/S8-2-2.mp4
    - assets/videos/Restaurant/S8-2-3.mp4
    - assets/videos/Restaurant/S8-2-4.mp4
    - assets/videos/Restaurant/S8-2-5.mp4
    - assets/videos/Restaurant/S8-2-6.mp4
    - assets/videos/Restaurant/S8-3.mp4
    - assets/videos/Phone/S9-1.mp4
    - assets/videos/Phone/S9-2-1.mp4
    - assets/videos/Phone/S9-2-2.mp4
    - assets/videos/Phone/S9-2-3.mp4
    - assets/videos/Phone/S9-2-4.mp4
    - assets/videos/Phone/S9-2-5.mp4
    - assets/videos/Phone/S9-3.mp4
    - assets/videos/Phone/S10-1.mp4
    - assets/videos/Phone/S10-2-1.mp4
    - assets/videos/Phone/S10-2-2.mp4
    - assets/videos/Phone/S10-3.mp4
    - assets/videos/Phone/S11-1.mp4
    - assets/videos/Phone/S11-2-1.mp4
    - assets/videos/Phone/S11-2-2.mp4
    - assets/videos/Phone/S11-2-3.mp4
    - assets/videos/Phone/S11-2-4.mp4
    - assets/videos/Phone/S11-3.mp4
    - assets/videos/Shopping/S12-1.mp4
    - assets/videos/Shopping/S12-2-1.mp4
    - assets/videos/Shopping/S12-2-1-check.mp4
    - assets/videos/Shopping/S12-2-3.mp4
    - assets/videos/Shopping/S12-2-4.mp4
    - assets/videos/Shopping/S12-2-5.mp4
    - assets/videos/Shopping/S12-2-6.mp4
    - assets/videos/Shopping/S12-3.mp4
    - assets/videos/Shopping/S13-1.mp4
    - assets/videos/Shopping/S13-2-1.mp4
    - assets/videos/Shopping/S13-2-2.mp4
    - assets/videos/Shopping/S13-2-3.mp4
    - assets/videos/Shopping/S13-2-4.mp4
    - assets/videos/Shopping/S13-3.mp4
    - assets/videos/Shopping/S14-1.mp4
    - assets/videos/Shopping/S14-2-1.mp4
    - assets/videos/Shopping/S14-2-2.mp4
    - assets/videos/Shopping/S14-2-2-check.mp4
    - assets/videos/Shopping/S14-2-3.mp4
    - assets/videos/Shopping/S14-2-4.mp4
    - assets/videos/Shopping/S14-2-5.mp4
    - assets/videos/Shopping/S14-2-5-check.mp4
    - assets/videos/Shopping/S14-2-6.mp4
    - assets/videos/Shopping/S14-2-7.mp4
    - assets/videos/Shopping/S14-3.mp4
    - assets/videos/Shopping/S15-1.mp4
    - assets/videos/Shopping/S15-2-1.mp4
    - assets/videos/Shopping/S15-2-2.mp4
    - assets/videos/Shopping/S15-2-3.mp4
    - assets/videos/Shopping/S15-2-4.mp4
    - assets/videos/Shopping/S15-2-5.mp4
    - assets/videos/Shopping/S15-3.mp4
    - assets/videos/Shopping/S16-1.mp4
    - assets/videos/Shopping/S16-2-1.mp4
    - assets/videos/Shopping/S16-2-2.mp4
    - assets/videos/Shopping/S16-2-3.mp4
    - assets/videos/Shopping/S16-2-4.mp4
    - assets/videos/Shopping/S16-2-5.mp4
    - assets/videos/Shopping/S16-2-6.mp4
    - assets/videos/Shopping/S16-2-6-check.mp4
    - assets/videos/Shopping/S16-3.mp4
    - assets/videos/Takeaway/S17-1.mp4
    - assets/videos/Takeaway/S17-2-1.mp4
    - assets/videos/Takeaway/S17-2-2.mp4
    - assets/videos/Takeaway/S17-2-3.mp4
    - assets/videos/Takeaway/S17-2-4.mp4
    - assets/videos/Takeaway/S17-2-5.mp4
    - assets/videos/Takeaway/S17-2-6.mp4
    - assets/videos/Takeaway/S17-2-7.mp4
    - assets/videos/Takeaway/S17-2-7-check.mp4
    - assets/videos/Takeaway/S17-2-8.mp4
    - assets/videos/Takeaway/S17-3.mp4
    - assets/videos/Takeaway/S18-1.mp4
    - assets/videos/Takeaway/S18-2-1.mp4
    - assets/videos/Takeaway/S18-2-2.mp4
    - assets/videos/Takeaway/S18-2-3.mp4
    - assets/videos/Takeaway/S18-2-4.mp4
    - assets/videos/Takeaway/S18-2-5.mp4
    - assets/videos/Takeaway/S18-2-6.png
    - assets/videos/Takeaway/S18-3.mp4
    - assets/videos/Takeaway/S19-1.mp4
    - assets/videos/Takeaway/S19-2-1.mp4
    - assets/videos/Takeaway/S19-2-2.mp4
    - assets/videos/Takeaway/S19-2-3.mp4
    - assets/videos/Takeaway/S19-2-4.mp4
    - assets/videos/Takeaway/S19-2-5.mp4
    - assets/videos/Takeaway/S19-2-6.mp4
    - assets/videos/Takeaway/S19-2-7.mp4
    - assets/videos/Takeaway/S19-3.mp4
    - assets/videos/Shopping2/S20-1.mp4
    - assets/videos/Shopping2/S20-2-1.mp4
    - assets/videos/Shopping2/S20-2-2.mp4
    - assets/videos/Shopping2/S20-2-2-check.mp4
    - assets/videos/Shopping2/S20-2-3.mp4
    - assets/videos/Shopping2/S20-2-4.mp4
    - assets/videos/Shopping2/S20-2-5.mp4
    - assets/videos/Shopping2/S20-3.mp4
    - assets/videos/Shopping2/S21-1.mp4
    - assets/videos/Shopping2/S21-2-1.mp4
    - assets/videos/Shopping2/S21-2-2.mp4
    - assets/videos/Shopping2/S21-2-3.mp4
    - assets/videos/Shopping2/S21-2-4.mp4
    - assets/videos/Shopping2/S21-2-5.mp4
    - assets/videos/Shopping2/S21-2-6.mp4
    - assets/videos/Shopping2/S21-2-7.mp4
    - assets/videos/Shopping2/S21-3.mp4
    - assets/videos/Shopping2/S22-1.mp4
    - assets/videos/Shopping2/S22-2-1.mp4
    - assets/videos/Shopping2/S22-2-2.mp4
    - assets/videos/Shopping2/S22-2-3.mp4
    - assets/videos/Shopping2/S22-2-4.mp4
    - assets/videos/Shopping2/S22-2-5.mp4
    - assets/videos/Shopping2/S22-2-6.mp4
    - assets/videos/Shopping2/S22-2-7.mp4
    - assets/videos/Shopping2/S22-2-7-check.mp4
    - assets/videos/Shopping2/S22-2-8.mp4
    - assets/videos/Shopping2/S22-3.mp4
    - assets/videos/Kamakura/S23-1.mp4
    - assets/videos/Kamakura/S23-2-1.mp4
    - assets/videos/Kamakura/S23-2-2.mp4
    - assets/videos/Kamakura/S23-2-3.mp4
    - assets/videos/Kamakura/S23-2-3-check.mp4
    - assets/videos/Kamakura/S23-2-4.mp4
    - assets/videos/Kamakura/S23-2-5.mp4
    - assets/videos/Kamakura/S23-2-6.mp4
    - assets/videos/Kamakura/S23-2-7.mp4
    - assets/videos/Kamakura/S23-2-8.mp4
    - assets/videos/Kamakura/S23-2-8-check.mp4
    - assets/videos/Kamakura/S23-3.mp4
    - assets/videos/Kamakura/S24-1.mp4
    - assets/videos/Kamakura/S24-2-1.mp4
    - assets/videos/Kamakura/S24-2-2.mp4
    - assets/videos/Kamakura/S24-2-3.mp4
    - assets/videos/Kamakura/S24-2-4.mp4
    - assets/videos/Kamakura/S24-2-5.mp4
    - assets/videos/Kamakura/S24-2-6.mp4
    - assets/videos/Kamakura/S24-2-7.mp4
    - assets/videos/Kamakura/S24-2-8.mp4
    - assets/videos/Kamakura/S24-3.mp4
    - assets/videos/Kamakura/S25-1.mp4
    - assets/videos/Kamakura/S25-2-1.mp4
    - assets/videos/Kamakura/S25-2-2.mp4
    - assets/videos/Kamakura/S25-2-3.mp4
    - assets/videos/Kamakura/S25-2-4.mp4
    - assets/videos/Kamakura/S25-3.mp4
    - assets/videos/Fastfood/S26-1.mp4
    - assets/videos/Fastfood/S26-2-1.mp4
    - assets/videos/Fastfood/S26-2-2.mp4
    - assets/videos/Fastfood/S26-2-3.mp4
    - assets/videos/Fastfood/S26-2-4.mp4
    - assets/videos/Fastfood/S26-2-5.mp4
    - assets/videos/Fastfood/S26-2-5-check.mp4
    - assets/videos/Fastfood/S26-2-6.mp4
    - assets/videos/Fastfood/S26-3.mp4
    - assets/videos/Fastfood/S27-1.mp4
    - assets/videos/Fastfood/S27-2-1.mp4
    - assets/videos/Fastfood/S27-2-2.mp4
    - assets/videos/Fastfood/S27-2-3.mp4
    - assets/videos/Fastfood/S27-2-4.mp4
    - assets/videos/Fastfood/S27-2-5.mp4
    - assets/videos/Fastfood/S27-2-6.mp4
    - assets/videos/Fastfood/S27-2-7.mp4
    - assets/videos/Fastfood/S27-3.mp4
    - assets/videos/Recommendations/S28-1.mp4
    - assets/videos/Recommendations/S28-2-1.mp4
    - assets/videos/Recommendations/S28-2-2.mp4
    - assets/videos/Recommendations/S28-2-3.png
    - assets/videos/Recommendations/S28-2-3-check.mp4
    - assets/videos/Recommendations/S28-2-4.png
    - assets/videos/Recommendations/S28-2-4-check.mp4
    - assets/videos/Recommendations/S28-2-5.mp4
    - assets/videos/Recommendations/S28-2-6.mp4
    - assets/videos/Recommendations/S28-2-7.mp4
    - assets/videos/Recommendations/S28-2-8.mp4
    - assets/videos/Recommendations/S28-2-9.mp4
    - assets/videos/Recommendations/S29-1.mp4
    - assets/videos/Recommendations/S29-2-1.mp4
    - assets/videos/Recommendations/S29-2-2.mp4
    - assets/videos/Recommendations/S29-2-3.mp4
    - assets/videos/Recommendations/S29-2-4.mp4
    - assets/videos/Recommendations/S29-2-5.mp4
    - assets/videos/Recommendations/S29-2-6.mp4
    - assets/videos/Recommendations/S29-2-6.png
    - assets/videos/Recommendations/S29-2-7.mp4
    - assets/videos/Recommendations/S29-2-8.mp4
    - assets/videos/Recommendations/S29-2-9.mp4
    - assets/videos/Recommendations/S29-3.mp4
    - assets/videos/Recommendations/S30-1.mp4
    - assets/videos/Recommendations/S30-2-1.mp4
    - assets/videos/Recommendations/S30-2-2.mp4
    - assets/videos/Recommendations/S30-2-3.mp4
    - assets/videos/Recommendations/S30-2-4.mp4
    - assets/videos/Recommendations/S30-2-5.mp4
    - assets/videos/Recommendations/S30-2-6.mp4
    - assets/videos/Recommendations/S30-2-7.mp4
    - assets/videos/Recommendations/S30-2-8.mp4
    - assets/videos/Recommendations/S30-2-9.mp4
    - assets/videos/Recommendations/S30-2-9.png
    - assets/videos/Recommendations/S30-2-10.mp4
    - assets/videos/Recommendations/S30-2-11.mp4
    - assets/videos/Recommendations/S30-2-12.mp4
    - assets/videos/Recommendations/S30-2-13.mp4
    - assets/videos/Recommendations/S30-2-14.mp4
    - assets/videos/Recommendations/S30-2-15.mp4
    - assets/videos/Recommendations/S30-2-16.mp4
    - assets/videos/Recommendations/S30-2-17.mp4
    - assets/videos/Recommendations/S30-2-18.mp4
    - assets/videos/Recommendations/S30-2-19.mp4
    - assets/videos/Recommendations/S30-2-20.mp4
    - assets/videos/Recommendations/S30-3.mp4
    - assets/pdf/1 Nou Sentence.pdf
    - assets/pdf/2 How to count.pdf
    - assets/pdf/3 ThisThatHereThere.pdf
    - assets/pdf/4 there is are.pdf
    - assets/pdf/5 Adjective.pdf
    - assets/pdf/6 Verb Sentence.pdf
    - assets/pdf/7 comb verb&particles.pdf
    - assets/pdf/8 want want to.pdf
    - assets/pdf/9 nai masu dic te.pdf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
